apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base/raw-app

replicas:
  - name: sample-app
    count: 3

labels:
  - includeSelectors: true
    pairs:
      environment: prod
